### ISSUE TITLE
[sam-backend] app 기능 추가(readyness, liveness)

### ISSUE THREAD

**Issue by iamnogada** [pit-ice/vrd-common#10]
[#9] 를 위한 상태체크 기능 로직 구현 필요.
Prototype에서는 단순 Get method만으로 처리.....

실업무는 로직 구현 필요.

**Comment by dongwookkim** [comment]
spring-boot-actuator 이용하여 처리함.

https://github.com/pit-ice/sam-backend/commit/a3793e813407e19e93aa1ed3152f891594b760ad
