### ISSUE TITLE
[sam-backend] spring 기본 외 설정은 별도 profile로 구분

### ISSUE THREAD

**Issue by iamnogada** [pit-ice/vrd-common#12]
[#11 ] 참고하여, 기준 마련하여 작성 필요

Phase별로 공통 값과 개별값 구분하여 처리.....

특히, datasource, jwt등의 민감정보는 개발소스가 아닌 kubernetes config or secret으로 관리 할 예정임.

**Comment by YoungkiHong** [comment]
* application.yaml 파일 jar 패키징시 분리 처리 
* configmap 에  application.yaml 포함 및 민감정보 환경변수 설정
* secretmap 에 민감정보 설정 및 deployment에서 환경변수로 전달. 



https://github.com/pit-ice/sam-backend/commit/7a22d3fd30e34426920913d97b405f7c69e5b0a9
