### ISSUE TITLE
[sam-frontend] Dockerfile 수정 필요

### ISSUE THREAD

**Issue by iamnogada** [pit-ice/vrd-common#4]
- nginx conf 파일 복사 제외
- nginx 설정은 docker run -v 또는 kuberetes configmap으로 대체
예) docker run --rm -it -v $(pwd)/file.json:/file.json test

**Comment by dongwookkim** [comment]
nginx config -> k8s configmap 으로 수정

https://github.com/pit-ice/sam-frontend/commit/e072fce99d105c421bd4487105813dd1169d0fbd
