### ISSUE TITLE
[sam-frontend]npm build 최적화 in Dockerfile

### ISSUE THREAD

**Issue by iamnogada** [pit-ice/vrd-common#8]
Build Container에서 
npm install 시에 devDependency항목을 제외 함으로써
최적화 가능.

https://docs.npmjs.com/cli/install 참고

**Comment by dongwookkim** [comment]
vue app 같은 경우는 빌드 후 dist폴더만 copy되어 node app과는 다르게 --production 옵션은 없어도 될듯합니다.

https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html#Real-World-Example

* production 옵션을 추가하면 
npm run build 명령어 실행될때 devDependency 항목의 라이브러리 사용하고있어 빌드 오류 발생 (@vue/cli-service, sass-loader 등.)
